Update compile.yml

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -13,7 +13,7 @@ jobs:
         with:
           fetch-depth: 0
       - run: |
-printf "[package]\nname=\"r\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[lib]\ncrate-type=[\"cdylib\"]\n[profile.release]\nopt-level=\"z\"\nlto=true\npanic=\"abort\"\ncodegen-units=1">Cargo.toml;mkdir -p src
+          printf "[package]\nname=\"r\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[lib]\ncrate-type=[\"cdylib\"]\n[profile.release]\nopt-level=\"z\"\nlto=true\npanic=\"abort\"\ncodegen-units=1">Cargo.toml;mkdir -p src
           cat<<'F'>src/lib.rs
           #![no_std]
           #[panic_handler]fn p(_:&core::panic::PanicInfo)->!{loop{}}
@@ -23,19 +23,17 @@ printf "[package]\nname=\"r\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[lib]\ncrate
           #[no_mangle]pub extern "C" fn Mx(a:f32,b:f32,d:f32)->f32{(a+b)/2.*d}
           F
       - run: |
-rustup target add wasm32-unknown-unknown
+          rustup target add wasm32-unknown-unknown
           cargo build --release --target wasm32-unknown-unknown
-          echo "WW='$(base64 -w 0 target/wasm32-unknown-unknown/release/r.wasm)';"
-> lib.js
+          echo "WW='$(base64 -w 0 target/wasm32-unknown-unknown/release/r.wasm)';" > lib.js
       - name: Push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-git config user.name bot
+          git config user.name bot
           git config user.email bot@github.com
           git add lib.js
-          if !
-git diff --staged --quiet; then
-            git commit -m "Update lib.js"
+          if ! git diff --staged --quiet; then
+            git commit -m "Update lib.js with Mx function"
             git push origin Rust
           fi
